/**
 * gradient-inline — runtime helper for generating inline SVG gradient definitions with
 * dynamic direction / focus. Used by Shape, Icon, Badge, Heading, etc. when `gradientDirection`
 * or `gradientFocus` is set (because the baked SVG defs in SvgGradientDefs.astro are fixed-angle).
 *
 * Reads from src/lib/gradient-catalogue.json (generated by scripts/build-gradients.mjs).
 */

import catalogue from './gradient-catalogue.json';

type Stop = { offset: number; token: string };
type Entry = { id: string; type: 'linear' | 'radial'; angle: number; stops: Stop[] };

const catalogueById: Record<string, Entry> = {};
for (const entry of catalogue as Entry[]) {
  catalogueById[entry.id] = entry;
}

/** CSS gradient direction → angle in degrees (matches tokens/gradients.css mapping). */
const directionAngles: Record<string, number> = {
  'vertical': 180,
  'vertical-reverse': 0,
  'horizontal': 90,
  'horizontal-reverse': 270,
  'diagonal': 135,
  'diagonal-reverse': 315,
  'diagonal-alt': 45,
  'diagonal-alt-reverse': 225,
};

/** Radial focus → cx/cy in objectBoundingBox coords. */
const focusCoords: Record<string, { cx: number; cy: number }> = {
  'center':       { cx: 0.5, cy: 0.5 },
  'top':          { cx: 0.5, cy: 0.0 },
  'bottom':       { cx: 0.5, cy: 1.0 },
  'left':         { cx: 0.0, cy: 0.5 },
  'right':        { cx: 1.0, cy: 0.5 },
  'top-left':     { cx: 0.0, cy: 0.0 },
  'top-right':    { cx: 1.0, cy: 0.0 },
  'bottom-left':  { cx: 0.0, cy: 1.0 },
  'bottom-right': { cx: 1.0, cy: 1.0 },
};

/** Convert CSS angle (deg) to SVG x1/y1/x2/y2 in objectBoundingBox (0-1) space. */
export function angleToCoords(angle: number) {
  const rad = ((angle - 90) * Math.PI) / 180;
  const cosA = Math.cos(rad);
  const sinA = Math.sin(rad);
  const t = 0.5 * (Math.abs(cosA) + Math.abs(sinA));
  const dx = cosA * t;
  const dy = sinA * t;
  return {
    x1: (0.5 - dx).toFixed(3),
    y1: (0.5 - dy).toFixed(3),
    x2: (0.5 + dx).toFixed(3),
    y2: (0.5 + dy).toFixed(3),
  };
}

/** Resolve a token name to a CSS var() reference.
 *   'primary-base'         → `var(--primary-base)`
 *   '--primary-base'       → `var(--primary-base)`
 *   'bg-context'           → `var(--_bg-context, var(--page-bg))`
 *   'alpha0:primary-base'  → `oklch(from var(--primary-base) l c h / 0)` — true transparent fade
 */
function tokenToVar(token: string): string {
  if (token === 'bg-context') return 'var(--_bg-context, var(--page-bg))';
  if (token.startsWith('alpha0:')) {
    const inner = token.slice(7);
    const ref = inner.startsWith('--') ? `var(${inner})` : `var(--${inner})`;
    return `oklch(from ${ref} l c h / 0)`;
  }
  if (token.startsWith('--')) return `var(${token})`;
  return `var(--${token})`;
}

export type InlineGradient =
  | { kind: 'linear'; id: string; x1: string; y1: string; x2: string; y2: string; stops: { offset: number; colour: string }[] }
  | { kind: 'radial'; id: string; cx: number; cy: number; r: string; stops: { offset: number; colour: string }[] }
  | null;

/**
 * Return the gradient's stop colours as CSS var() references for use in colour-cycle animations.
 * Returns null if the gradient id isn't in the catalogue.
 */
export function getGradientStopColours(gradientId: string): string[] | null {
  const entry = catalogueById[gradientId];
  if (!entry) return null;
  return entry.stops.map((s) => tokenToVar(s.token));
}

/**
 * Look up a gradient by id and return inline SVG def data.
 * Returns null if the gradient id isn't in the catalogue.
 *
 * For linear gradients: computes x1/y1/x2/y2 from the direction (falls back to entry's default angle).
 * For radial gradients: computes cx/cy/r from the focus (falls back to center).
 */
export function resolveInlineGradient(
  gradientId: string,
  opts: { direction?: string; focus?: string } = {}
): InlineGradient {
  const entry = catalogueById[gradientId];
  if (!entry) return null;

  const id = `inline-${gradientId}-${Math.random().toString(36).substring(2, 9)}`;
  const stops = entry.stops.map((s) => ({ offset: s.offset, colour: tokenToVar(s.token) }));

  if (entry.type === 'linear') {
    const angle = opts.direction && directionAngles[opts.direction] !== undefined
      ? directionAngles[opts.direction]
      : entry.angle;
    const coords = angleToCoords(angle);
    return { kind: 'linear', id, ...coords, stops };
  }

  // radial
  const focus = focusCoords[opts.focus || 'center'] ?? focusCoords.center;
  const r = Math.sqrt(
    Math.pow(Math.max(focus.cx, 1 - focus.cx), 2) +
    Math.pow(Math.max(focus.cy, 1 - focus.cy), 2)
  ).toFixed(3);
  return { kind: 'radial', id, cx: focus.cx, cy: focus.cy, r, stops };
}
