-- 003: Lottie → static fallback mappings
-- Auto-generated by seed-lottie.ts

INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_52bkg1esoh9h', 'a_6a0wuw06fw5r');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_1ju13hxt9egs', 'a_1tvtk0riiksu');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_19x1u6vs2krx', 'a_sp5b4riyqo95');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_eu4m51hvzp18', 'a_of0dy7os3bm4');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_czm6ycy7kyba', 'a_rp7w6a27p8li');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_vbn3ddq67fpb', 'a_057dvr1tf8oi');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_xwvpo1pyx905', 'a_m5xtut1ctyzq');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_zaush1fiitii', 'a_38uz8cvrxpo7');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_y3k6mz9uqj0f', 'a_38uz8cvrxpo7');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_2gxkuo4sz20z', 'a_38uz8cvrxpo7');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_tlpwi8hd2s6m', 'a_38uz8cvrxpo7');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_omh33oqrqpzh', 'a_gdrxhrazhpa7');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_pkk77nto1jui', 'a_16tanaq42ac6');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_3n2jf0ryo1se', 'a_9biv5jehco24');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_ek6fp0a5s0ca', 'a_0gi2y7mnuity');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_0vowiii69c3i', 'a_cyumj4sd0btx');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_9vataed0kakt', 'a_uqdcc8r8ct6t');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_m04e3bxe50kx', 'a_353tjpmjiz3v');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_y560bqo4ltmb', 'a_6a0wuw06fw5r');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_rajvcwxzu80f', 'a_5dev92vxxuiq');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_e24k0xotbafs', 'a_cae90rnz7y9a');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_gfl3atehix2k', 'a_0gi2y7mnuity');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_pq26sp2erb3l', 'a_67e8du25biw7');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_81ld7lcan9a9', 'a_y99i2lyj67xi');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_pakps831q33s', 'a_y99i2lyj67xi');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_bt419p9vfter', 'a_y99i2lyj67xi');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_sjev01job03p', 'a_y99i2lyj67xi');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_4f725g7f28g2', 'a_y99i2lyj67xi');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_rin81kn5mqkb', 'a_g2nw3bdyl1zx');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_ri9k1y4mx7hl', 'a_2utskpq9uiws');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_rvgie2k39spd', 'a_5ovfxl89zb1f');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_fy5eeaxil60w', 'a_0zzin371yk6h');
INSERT OR IGNORE INTO lottie_mappings (lottie_asset_id, static_asset_id) VALUES ('a_cwc5xxpgmy0u', 'a_skynvmypsiol');
