name = "asset-library"
main = "src/index.ts"
compatibility_date = "2026-02-26"

[[d1_databases]]
binding = "DB"
database_name = "asset-library"
database_id = "d7b8c992-52cf-4841-be95-39965742ec05"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "asset-library"

# Set via: wrangler secret put API_TOKEN
# [vars]
# API_TOKEN = "do-not-put-secrets-here"
